config/routes.rb
Rails.application.routes.draw do
  get 'main/sign_in'

  get '/install', to: 'main#install'

  get '/barcode-setup', to: 'main#barcode_setup'

  get '/manual-setup', to: 'main#manual_setup'

  get '/verify-passcode', to: 'main#passcode_setup'

  get '/success', to: 'main#success'

  root 'main#sign_in'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def sign_in
  end

  def install
  end

  def barcode_setup
  end

  def manual_setup
  end

  def passcode_setup
  end

  def success
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Pivotal
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body{ class: "#{controller_name} #{action_name}"}
    .container.mtxxl
      = yield

app/views/main/barcode_setup.html.haml
.row
  .col-md-12.col-md-push-6
    .panel.panel-basic-alt.phxl.pvxl
      .panel-body
        %h1.man Acme Inc. Identity
        %h2.mtxl Setup Google Authenticator
        %p.mtxl
          You will be asked for a passcode when you sign in from an unrecognize computer.
        %ol.phxl.pvxl
          %li Open Google Authenticator on your phone.
          %li Tap the "+" button.
          %li Tap "Scan barcode".
          %li Scan this barcode:
        = image_tag 'qrcode.png'
        %p.mtl= "Can’t scan barcode? See <a href='#{manual_setup_path}'>manual setup instructions</a>.".html_safe
= render partial: 'partials/prototype_msg', locals: { the_link: verify_passcode_path, show_note: true }

app/views/main/install.html.haml
.row
  .col-md-12.col-md-push-6
    .panel.panel-basic-alt.phxl.pvxl
      .panel-body
        %h1 Acme Inc. Identity
        %h2.mtxl Setup Two-Factor Authentication
        %p.mtxl
          You will be asked for a passcode when you sign in from an unrecognized computer.
        %ol.phxl.pvxl
          %li Open the App Store on your iPhone or Google Play on your Android.
          %li Search for Google Authenticator.
          %li Download and Install Google Authenticator.
        = link_to "Continue to Setup", barcode_setup_path, class: 'btn btn-default'

app/views/main/manual_setup.html.haml
.row
  .col-md-12.col-md-push-6
    .panel.panel-basic-alt.phxl.pvxl
      .panel-body
        %h1.man Acme Inc. Identity
        %h2.mtxl Manual Setup Instructions
        %p.mtxl
          You will be asked for a passcode when you sign in from an unrecognize computer.
        %ol.phxl.pvxl
          %li Open Google Authenticator on your phone.
          %li Tap the '+' button.
          %li Tap 'Manual entry'
          %li
            Enter the following in the 'Account' field:
            %p.type-brand-6
              Acme: email@example.com
          %li
            Enter the following in the 'Key' field:
            %p.type-brand-6
              U3KD9J3O10MVN313
          %li Tap the 'Done' button on your phone.
= render partial: 'partials/prototype_msg', locals: { the_link: verify_passcode_path, show_note: true }

app/views/main/passcode_setup.html.haml
.row
  .col-md-12.col-md-push-6
    .panel.panel-basic-alt.phxl.pvxl
      .panel-body
        %h1.man Acme Inc. Identity
        %h2.mtxl Setup Google Authenticator
        %p.mtxl
          Enter the 6-digit code displayed in Google Authenticator app:
        %form.form-inline.passcode{ action: '/success', method: 'get'}
          %input.form-control.mrs.txt-c.em-high#pc_1{ type: 'number', style: 'max-width: 48px;', value: 3}
          %input.form-control.mrs.txt-c.em-high#pc_2{ type: 'number', style: 'max-width: 48px;', value: 2}
          %input.form-control.mrxl.txt-c.em-high#pc_3{ type: 'number', style: 'max-width: 48px;', value: 1}
          %input.form-control.mrs.txt-c.em-high#pc_4{ type: 'number', style: 'max-width: 48px;', value: 4}
          %input.form-control.mrs.txt-c.em-high#pc_5{ type: 'number', style: 'max-width: 48px;', value: 5}
          %input.form-control.txt-c.em-high#pc_6{ type: 'number', style: 'max-width: 48px;', 'max-length' => 1, value: 6}
          %button.btn.btn-highlight.mlxl 
            Verify
        %p.type-error-3.type-sm.mtm
          Incorrect code, please try again.
= render partial: 'partials/prototype_msg', locals: { the_link: success_path, show_note: false }

app/views/main/sign_in.html.haml
.txt-c
  = link_to install_path do
    = image_tag 'login.png'

app/views/main/success.html.haml
.row
  .col-md-12
    %h1 Kaleidoscope
  .col-md-12.txt-r
    .h1.type-sm.ptl= link_to "Sign Out", root_path
.row
  .col-md-24
    .mtl
      = image_tag 'kaleidoscope-fake.png'
    

app/views/partials/_prototype_msg.html.haml
.txt-c.mtxxl{ style: "color: magenta;"}
  - if show_note
    NOTE: This screen will auto-advance.
    %br
  = link_to "Next Prototype Page", the_link, style: "color: magenta; text-decoration: underline;"